// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
	properties: {
		grant_type: {
			anyOf: [
				{
					type: 'string',
					pattern: '^password$',
				},
				{
					type: 'null',
				},
			],
			title: 'Grant Type',
		},
		username: {
			type: 'string',
			title: 'Username',
		},
		password: {
			type: 'string',
			format: 'password',
			title: 'Password',
		},
		scope: {
			type: 'string',
			title: 'Scope',
			default: '',
		},
		client_id: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Client Id',
		},
		client_secret: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			format: 'password',
			title: 'Client Secret',
		},
	},
	type: 'object',
	required: ['username', 'password'],
	title: 'Body_login-login_access_token',
} as const

export const CensusDataSchema = {
	properties: {
		academicYear: {
			type: 'integer',
			title: 'Academicyear',
		},
		aggregationLevel: {
			type: 'string',
			title: 'Aggregationlevel',
		},
		cdsCode: {
			type: 'string',
			maxLength: 14,
			title: 'Cdscode',
		},
		charter: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Charter',
		},
		reportingCategory: {
			type: 'string',
			maxLength: 255,
			title: 'Reportingcategory',
		},
		totalEnr: {
			type: 'integer',
			title: 'Totalenr',
			default: 0,
		},
		grTk: {
			type: 'integer',
			title: 'Grtk',
			default: 0,
		},
		grKn: {
			type: 'integer',
			title: 'Grkn',
			default: 0,
		},
		gr1: {
			type: 'integer',
			title: 'Gr1',
			default: 0,
		},
		gr2: {
			type: 'integer',
			title: 'Gr2',
			default: 0,
		},
		gr3: {
			type: 'integer',
			title: 'Gr3',
			default: 0,
		},
		gr4: {
			type: 'integer',
			title: 'Gr4',
			default: 0,
		},
		gr5: {
			type: 'integer',
			title: 'Gr5',
			default: 0,
		},
		gr6: {
			type: 'integer',
			title: 'Gr6',
			default: 0,
		},
		gr7: {
			type: 'integer',
			title: 'Gr7',
			default: 0,
		},
		gr8: {
			type: 'integer',
			title: 'Gr8',
			default: 0,
		},
		gr9: {
			type: 'integer',
			title: 'Gr9',
			default: 0,
		},
		gr10: {
			type: 'integer',
			title: 'Gr10',
			default: 0,
		},
		gr11: {
			type: 'integer',
			title: 'Gr11',
			default: 0,
		},
		gr12: {
			type: 'integer',
			title: 'Gr12',
			default: 0,
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
	},
	type: 'object',
	required: ['academicYear', 'aggregationLevel', 'cdsCode', 'reportingCategory'],
	title: 'CensusData',
} as const

export const DashboardSummaryResponseSchema = {
	properties: {
		cds: {
			type: 'string',
			title: 'Cds',
		},
		testYear: {
			type: 'string',
			title: 'Testyear',
		},
		indicators: {
			items: {
				$ref: '#/components/schemas/IndicatorSummary',
			},
			type: 'array',
			title: 'Indicators',
		},
	},
	type: 'object',
	required: ['cds', 'testYear', 'indicators'],
	title: 'DashboardSummaryResponse',
	description: 'Response containing multiple tests for a school/district/county.',
} as const

export const EquityGroupSummarySchema = {
	properties: {
		studentGroup: {
			type: 'string',
			title: 'Studentgroup',
		},
		overallMetAndAbovePct: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Overallmetandabovepct',
		},
		studentsTested: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentstested',
		},
	},
	type: 'object',
	required: ['studentGroup'],
	title: 'EquityGroupSummary',
	description: 'Summary of a student group for the equity report.',
} as const

export const EquityReportResponseSchema = {
	properties: {
		cds: {
			type: 'string',
			title: 'Cds',
		},
		testId: {
			type: 'string',
			title: 'Testid',
		},
		testYear: {
			type: 'string',
			title: 'Testyear',
		},
		groups: {
			items: {
				$ref: '#/components/schemas/EquityGroupSummary',
			},
			type: 'array',
			title: 'Groups',
		},
	},
	type: 'object',
	required: ['cds', 'testId', 'testYear', 'groups'],
	title: 'EquityReportResponse',
	description: 'Response containing student group breakdown for a test.',
} as const

export const ForcePasswordResetRequestSchema = {
	properties: {
		emails: {
			items: {
				type: 'string',
				format: 'email',
			},
			type: 'array',
			title: 'Emails',
		},
		includeAllActiveUsers: {
			type: 'boolean',
			title: 'Includeallactiveusers',
			default: false,
		},
	},
	type: 'object',
	title: 'ForcePasswordResetRequest',
} as const

export const HTTPValidationErrorSchema = {
	properties: {
		detail: {
			items: {
				$ref: '#/components/schemas/ValidationError',
			},
			type: 'array',
			title: 'Detail',
		},
	},
	type: 'object',
	title: 'HTTPValidationError',
} as const

export const IndicatorSummarySchema = {
	properties: {
		testId: {
			type: 'string',
			title: 'Testid',
		},
		testType: {
			type: 'string',
			title: 'Testtype',
		},
		grade: {
			type: 'string',
			title: 'Grade',
		},
		studentsEnrolled: {
			type: 'string',
			title: 'Studentsenrolled',
		},
		studentsTested: {
			type: 'string',
			title: 'Studentstested',
		},
		overallMeanScaleScore: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Overallmeanscalescore',
		},
		overallMetAndAbovePct: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Overallmetandabovepct',
		},
		levels: {
			anyOf: [
				{
					additionalProperties: {
						type: 'number',
					},
					type: 'object',
				},
				{
					type: 'null',
				},
			],
			title: 'Levels',
		},
	},
	type: 'object',
	required: ['testId', 'testType', 'grade', 'studentsEnrolled', 'studentsTested'],
	title: 'IndicatorSummary',
	description: 'Summary of a specific CAASPP/ELPAC test result.',
} as const

export const ItemCreateSchema = {
	properties: {
		title: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
	},
	type: 'object',
	required: ['title'],
	title: 'ItemCreate',
	description: 'Properties to receive on item creation',
} as const

export const ItemPublicSchema = {
	properties: {
		title: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		ownerId: {
			type: 'string',
			format: 'uuid',
			title: 'Ownerid',
		},
		createdAt: {
			anyOf: [
				{
					type: 'string',
					format: 'date-time',
				},
				{
					type: 'null',
				},
			],
			title: 'Createdat',
		},
	},
	type: 'object',
	required: ['title', 'id', 'ownerId'],
	title: 'ItemPublic',
	description: 'Properties to return via API, id is always required',
} as const

export const ItemUpdateSchema = {
	properties: {
		title: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					minLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
	},
	type: 'object',
	title: 'ItemUpdate',
	description: 'Properties to receive on item update',
} as const

export const ItemsPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/ItemPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'ItemsPublic',
} as const

export const MessageSchema = {
	properties: {
		message: {
			type: 'string',
			title: 'Message',
		},
	},
	type: 'object',
	required: ['message'],
	title: 'Message',
	description: 'Generic message',
} as const

export const NewPasswordSchema = {
	properties: {
		token: {
			type: 'string',
			title: 'Token',
		},
		newPassword: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Newpassword',
		},
	},
	type: 'object',
	required: ['token', 'newPassword'],
	title: 'NewPassword',
} as const

export const PrivateUserCreateSchema = {
	properties: {
		email: {
			type: 'string',
			title: 'Email',
		},
		password: {
			type: 'string',
			title: 'Password',
		},
		full_name: {
			type: 'string',
			title: 'Full Name',
		},
		is_verified: {
			type: 'boolean',
			title: 'Is Verified',
			default: false,
		},
	},
	type: 'object',
	required: ['email', 'password', 'full_name'],
	title: 'PrivateUserCreate',
} as const

export const SchoolPublicSchema = {
	properties: {
		cdsCode: {
			type: 'string',
			maxLength: 255,
			title: 'Cdscode',
		},
		ncesDist: {
			type: 'string',
			maxLength: 255,
			title: 'Ncesdist',
		},
		ncesSchool: {
			type: 'string',
			maxLength: 255,
			title: 'Ncesschool',
		},
		schoolCode: {
			type: 'string',
			maxLength: 255,
			title: 'Schoolcode',
		},
		statusType: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Statustype',
		},
		county: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'County',
		},
		district: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'District',
		},
		school: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'School',
		},
		street: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Street',
		},
		streetAbr: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Streetabr',
		},
		city: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'City',
		},
		zip: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Zip',
		},
		state: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'State',
		},
		mailStreet: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Mailstreet',
		},
		mailStreetAbr: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Mailstreetabr',
		},
		mailCity: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Mailcity',
		},
		mailZip: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Mailzip',
		},
		mailState: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Mailstate',
		},
		phone: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Phone',
		},
		ext: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Ext',
		},
		faxNumber: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Faxnumber',
		},
		website: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Website',
		},
		openDate: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Opendate',
		},
		closedDate: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Closeddate',
		},
		charter: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Charter',
		},
		charterNum: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Charternum',
		},
		fundingType: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fundingtype',
		},
		doc: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Doc',
		},
		docType: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Doctype',
		},
		soc: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Soc',
		},
		socType: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Soctype',
		},
		edopsCode: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Edopscode',
		},
		edopsName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Edopsname',
		},
		eilCode: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Eilcode',
		},
		eilName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Eilname',
		},
		gsOffered: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Gsoffered',
		},
		gsServed: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Gsserved',
		},
		virtual: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Virtual',
		},
		magnet: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Magnet',
		},
		yearRoundYn: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Yearroundyn',
		},
		federalDfcDistrictId: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Federaldfcdistrictid',
		},
		latitude: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Latitude',
		},
		longitude: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Longitude',
		},
		admFname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Admfname',
		},
		admLname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Admlname',
		},
		lastUpDate: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Lastupdate',
		},
		multilingual: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Multilingual',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
	},
	type: 'object',
	required: ['cdsCode', 'ncesDist', 'ncesSchool', 'schoolCode', 'id'],
	title: 'SchoolPublic',
} as const

export const SchoolSummarySchema = {
	properties: {
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		school: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'School',
		},
		city: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'City',
		},
		county: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'County',
		},
		cdsCode: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Cdscode',
		},
		schoolCode: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Schoolcode',
		},
	},
	type: 'object',
	required: ['id'],
	title: 'SchoolSummary',
} as const

export const SchoolsPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/SchoolPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'SchoolsPublic',
} as const

export const SchoolsSummarySchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/SchoolSummary',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'SchoolsSummary',
} as const

export const TokenSchema = {
	properties: {
		accessToken: {
			type: 'string',
			title: 'Accesstoken',
		},
		tokenType: {
			type: 'string',
			title: 'Tokentype',
			default: 'bearer',
		},
	},
	type: 'object',
	required: ['accessToken'],
	title: 'Token',
	description: 'A JSON payload containing the access token.',
} as const

export const UpdatePasswordSchema = {
	properties: {
		currentPassword: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Currentpassword',
		},
		newPassword: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Newpassword',
		},
	},
	type: 'object',
	required: ['currentPassword', 'newPassword'],
	title: 'UpdatePassword',
} as const

export const UserCreateSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		isActive: {
			type: 'boolean',
			title: 'Isactive',
			default: true,
		},
		isSuperuser: {
			type: 'boolean',
			title: 'Issuperuser',
			default: false,
		},
		fullName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fullname',
		},
		password: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Password',
		},
	},
	type: 'object',
	required: ['email', 'password'],
	title: 'UserCreate',
} as const

export const UserPreferencesUpdateSchema = {
	properties: {
		lastViewedCds: {
			anyOf: [
				{
					type: 'string',
					maxLength: 14,
				},
				{
					type: 'null',
				},
			],
			title: 'Lastviewedcds',
		},
	},
	type: 'object',
	title: 'UserPreferencesUpdate',
} as const

export const UserPublicSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		isActive: {
			type: 'boolean',
			title: 'Isactive',
			default: true,
		},
		isSuperuser: {
			type: 'boolean',
			title: 'Issuperuser',
			default: false,
		},
		fullName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fullname',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		createdAt: {
			anyOf: [
				{
					type: 'string',
					format: 'date-time',
				},
				{
					type: 'null',
				},
			],
			title: 'Createdat',
		},
		forcePasswordReset: {
			type: 'boolean',
			title: 'Forcepasswordreset',
			default: false,
		},
	},
	type: 'object',
	required: ['email', 'id'],
	title: 'UserPublic',
} as const

export const UserRegisterSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		password: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Password',
		},
		fullName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fullname',
		},
	},
	type: 'object',
	required: ['email', 'password'],
	title: 'UserRegister',
} as const

export const UserUpdateSchema = {
	properties: {
		email: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					format: 'email',
				},
				{
					type: 'null',
				},
			],
			title: 'Email',
		},
		isActive: {
			type: 'boolean',
			title: 'Isactive',
			default: true,
		},
		isSuperuser: {
			type: 'boolean',
			title: 'Issuperuser',
			default: false,
		},
		fullName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fullname',
		},
		password: {
			anyOf: [
				{
					type: 'string',
					maxLength: 128,
					minLength: 8,
				},
				{
					type: 'null',
				},
			],
			title: 'Password',
		},
		forcePasswordReset: {
			anyOf: [
				{
					type: 'boolean',
				},
				{
					type: 'null',
				},
			],
			title: 'Forcepasswordreset',
		},
	},
	type: 'object',
	title: 'UserUpdate',
} as const

export const UserUpdateMeSchema = {
	properties: {
		fullName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fullname',
		},
		email: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					format: 'email',
				},
				{
					type: 'null',
				},
			],
			title: 'Email',
		},
		lastViewedCds: {
			anyOf: [
				{
					type: 'string',
					maxLength: 14,
				},
				{
					type: 'null',
				},
			],
			title: 'Lastviewedcds',
		},
	},
	type: 'object',
	title: 'UserUpdateMe',
} as const

export const UsersPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/UserPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'UsersPublic',
} as const

export const ValidationErrorSchema = {
	properties: {
		loc: {
			items: {
				anyOf: [
					{
						type: 'string',
					},
					{
						type: 'integer',
					},
				],
			},
			type: 'array',
			title: 'Location',
		},
		msg: {
			type: 'string',
			title: 'Message',
		},
		type: {
			type: 'string',
			title: 'Error Type',
		},
		input: {
			title: 'Input',
		},
		ctx: {
			type: 'object',
			title: 'Context',
		},
	},
	type: 'object',
	required: ['loc', 'msg', 'type'],
	title: 'ValidationError',
} as const
