// This file is auto-generated by @hey-api/openapi-ts

export const AssessmentPublicSchema = {
	properties: {
		testId: {
			type: 'integer',
			title: 'Testid',
		},
		code: {
			type: 'string',
			title: 'Code',
		},
		program: {
			$ref: '#/components/schemas/Program',
		},
		testType: {
			type: 'string',
			title: 'Testtype',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		shortName: {
			type: 'string',
			title: 'Shortname',
		},
		subject: {
			type: 'string',
			title: 'Subject',
		},
		isAlternate: {
			type: 'boolean',
			title: 'Isalternate',
		},
		sortOrder: {
			type: 'integer',
			title: 'Sortorder',
		},
		levelScheme: {
			$ref: '#/components/schemas/LevelSchemePublic',
		},
		subscores: {
			items: {
				$ref: '#/components/schemas/SubscorePublic',
			},
			type: 'array',
			title: 'Subscores',
		},
		grades: {
			items: {
				type: 'string',
			},
			type: 'array',
			title: 'Grades',
		},
		gradesNote: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Gradesnote',
		},
	},
	type: 'object',
	required: [
		'testId',
		'code',
		'program',
		'testType',
		'name',
		'shortName',
		'subject',
		'isAlternate',
		'sortOrder',
		'levelScheme',
		'subscores',
		'grades',
	],
	title: 'AssessmentPublic',
	description: 'A test, described for one administration year.',
} as const

export const Body_login_login_access_tokenSchema = {
	properties: {
		grant_type: {
			anyOf: [
				{
					type: 'string',
					pattern: '^password$',
				},
				{
					type: 'null',
				},
			],
			title: 'Grant Type',
		},
		username: {
			type: 'string',
			title: 'Username',
		},
		password: {
			type: 'string',
			format: 'password',
			title: 'Password',
		},
		scope: {
			type: 'string',
			title: 'Scope',
			default: '',
		},
		client_id: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Client Id',
		},
		client_secret: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			format: 'password',
			title: 'Client Secret',
		},
	},
	type: 'object',
	required: ['username', 'password'],
	title: 'Body_login-login_access_token',
} as const

export const CatalogSchema = {
	properties: {
		testYear: {
			type: 'integer',
			title: 'Testyear',
		},
		years: {
			items: {
				type: 'integer',
			},
			type: 'array',
			title: 'Years',
		},
		assessments: {
			items: {
				$ref: '#/components/schemas/AssessmentPublic',
			},
			type: 'array',
			title: 'Assessments',
		},
		studentGroups: {
			items: {
				$ref: '#/components/schemas/StudentGroupPublic',
			},
			type: 'array',
			title: 'Studentgroups',
		},
		grades: {
			items: {
				$ref: '#/components/schemas/GradePublic',
			},
			type: 'array',
			title: 'Grades',
		},
	},
	type: 'object',
	required: ['testYear', 'years', 'assessments', 'studentGroups', 'grades'],
	title: 'Catalog',
	description: 'Everything a client needs to build the report controls.',
} as const

export const CensusDataSchema = {
	properties: {
		academicYear: {
			type: 'integer',
			title: 'Academicyear',
		},
		aggregationLevel: {
			type: 'string',
			title: 'Aggregationlevel',
		},
		cdsCode: {
			type: 'string',
			maxLength: 14,
			title: 'Cdscode',
		},
		charter: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Charter',
		},
		reportingCategory: {
			type: 'string',
			maxLength: 255,
			title: 'Reportingcategory',
		},
		totalEnr: {
			type: 'integer',
			title: 'Totalenr',
			default: 0,
		},
		grTk: {
			type: 'integer',
			title: 'Grtk',
			default: 0,
		},
		grKn: {
			type: 'integer',
			title: 'Grkn',
			default: 0,
		},
		gr1: {
			type: 'integer',
			title: 'Gr1',
			default: 0,
		},
		gr2: {
			type: 'integer',
			title: 'Gr2',
			default: 0,
		},
		gr3: {
			type: 'integer',
			title: 'Gr3',
			default: 0,
		},
		gr4: {
			type: 'integer',
			title: 'Gr4',
			default: 0,
		},
		gr5: {
			type: 'integer',
			title: 'Gr5',
			default: 0,
		},
		gr6: {
			type: 'integer',
			title: 'Gr6',
			default: 0,
		},
		gr7: {
			type: 'integer',
			title: 'Gr7',
			default: 0,
		},
		gr8: {
			type: 'integer',
			title: 'Gr8',
			default: 0,
		},
		gr9: {
			type: 'integer',
			title: 'Gr9',
			default: 0,
		},
		gr10: {
			type: 'integer',
			title: 'Gr10',
			default: 0,
		},
		gr11: {
			type: 'integer',
			title: 'Gr11',
			default: 0,
		},
		gr12: {
			type: 'integer',
			title: 'Gr12',
			default: 0,
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
	},
	type: 'object',
	required: ['academicYear', 'aggregationLevel', 'cdsCode', 'reportingCategory'],
	title: 'CensusData',
} as const

export const CharterFundingSchema = {
	type: 'string',
	enum: ['direct', 'local'],
	title: 'CharterFunding',
	description: 'How a charter school is funded, per the entity ``Type ID``.',
} as const

export const ChildEntityReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		testYear: {
			type: 'integer',
			title: 'Testyear',
		},
		testId: {
			type: 'integer',
			title: 'Testid',
		},
		studentGroupId: {
			type: 'integer',
			title: 'Studentgroupid',
		},
		grade: {
			type: 'string',
			title: 'Grade',
		},
		childLevel: {
			$ref: '#/components/schemas/EntityLevel',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
		data: {
			items: {
				$ref: '#/components/schemas/ChildEntityResult',
			},
			type: 'array',
			title: 'Data',
		},
	},
	type: 'object',
	required: [
		'entity',
		'testYear',
		'testId',
		'studentGroupId',
		'grade',
		'childLevel',
		'count',
		'data',
	],
	title: 'ChildEntityReport',
} as const

export const ChildEntityResultSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		studentsTested: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentstested',
		},
		meanScaleScore: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Meanscalescore',
		},
		metOrAbovePct: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Metorabovepct',
		},
		suppressed: {
			type: 'boolean',
			title: 'Suppressed',
			default: false,
		},
	},
	type: 'object',
	required: ['entity'],
	title: 'ChildEntityResult',
	description: 'One county, district or school inside the requested entity.',
} as const

export const ChildIndicatorReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		reportingYear: {
			type: 'integer',
			title: 'Reportingyear',
		},
		indicatorCode: {
			type: 'string',
			title: 'Indicatorcode',
		},
		studentGroupCode: {
			type: 'string',
			title: 'Studentgroupcode',
		},
		children: {
			items: {
				$ref: '#/components/schemas/ChildIndicatorResult',
			},
			type: 'array',
			title: 'Children',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['entity', 'reportingYear', 'indicatorCode', 'studentGroupCode', 'children', 'count'],
	title: 'ChildIndicatorReport',
	description: 'The entities inside a district or county, ranked on one indicator.',
} as const

export const ChildIndicatorResultSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		result: {
			$ref: '#/components/schemas/IndicatorResult',
		},
	},
	type: 'object',
	required: ['entity', 'result'],
	title: 'ChildIndicatorResult',
	description: "One child entity's result, for ranking within a district or county.",
} as const

export const CompareReportSchema = {
	properties: {
		testYear: {
			type: 'integer',
			title: 'Testyear',
		},
		testId: {
			type: 'integer',
			title: 'Testid',
		},
		studentGroupId: {
			type: 'integer',
			title: 'Studentgroupid',
		},
		grade: {
			type: 'string',
			title: 'Grade',
		},
		entries: {
			items: {
				$ref: '#/components/schemas/EntityResults',
			},
			type: 'array',
			title: 'Entries',
		},
	},
	type: 'object',
	required: ['testYear', 'testId', 'studentGroupId', 'grade', 'entries'],
	title: 'CompareReport',
	description: 'Side-by-side results for an explicit list of entities.',
} as const

export const DashboardCatalogSchema = {
	properties: {
		reportingYear: {
			type: 'integer',
			title: 'Reportingyear',
		},
		years: {
			items: {
				type: 'integer',
			},
			type: 'array',
			title: 'Years',
		},
		indicators: {
			items: {
				$ref: '#/components/schemas/IndicatorPublic',
			},
			type: 'array',
			title: 'Indicators',
		},
		studentGroups: {
			items: {
				$ref: '#/components/schemas/StudentGroupCodePublic',
			},
			type: 'array',
			title: 'Studentgroups',
		},
		colors: {
			additionalProperties: {
				type: 'string',
			},
			type: 'object',
			title: 'Colors',
			default: {
				1: 'Red',
				2: 'Orange',
				3: 'Yellow',
				4: 'Green',
				5: 'Blue',
			},
		},
	},
	type: 'object',
	required: ['reportingYear', 'years', 'indicators', 'studentGroups'],
	title: 'DashboardCatalog',
	description: 'Everything needed to populate the accountability filters.',
} as const

export const EntityAncestrySchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		ancestors: {
			items: {
				$ref: '#/components/schemas/EntityPublic',
			},
			type: 'array',
			title: 'Ancestors',
		},
	},
	type: 'object',
	required: ['entity', 'ancestors'],
	title: 'EntityAncestry',
	description: 'An entity together with the entities it rolls up into.',
} as const

export const EntityLevelSchema = {
	type: 'string',
	enum: ['state', 'county', 'district', 'school'],
	title: 'EntityLevel',
	description: 'Reporting level of an entity in a research file.',
} as const

export const EntityListSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/EntityPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'EntityList',
} as const

export const EntityPublicSchema = {
	properties: {
		cdsCode: {
			type: 'string',
			title: 'Cdscode',
		},
		displayName: {
			type: 'string',
			title: 'Displayname',
		},
		entityLevel: {
			$ref: '#/components/schemas/EntityLevel',
		},
		countyCode: {
			type: 'string',
			title: 'Countycode',
		},
		districtCode: {
			type: 'string',
			title: 'Districtcode',
		},
		schoolCode: {
			type: 'string',
			title: 'Schoolcode',
		},
		countyName: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Countyname',
		},
		districtName: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Districtname',
		},
		schoolName: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Schoolname',
		},
		zipCode: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Zipcode',
		},
		isCharter: {
			type: 'boolean',
			title: 'Ischarter',
			default: false,
		},
		charterFunding: {
			anyOf: [
				{
					$ref: '#/components/schemas/CharterFunding',
				},
				{
					type: 'null',
				},
			],
		},
		parentCdsCode: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Parentcdscode',
		},
		firstTestYear: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Firsttestyear',
		},
		lastTestYear: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Lasttestyear',
		},
	},
	type: 'object',
	required: ['cdsCode', 'displayName', 'entityLevel', 'countyCode', 'districtCode', 'schoolCode'],
	title: 'EntityPublic',
	description: 'An entity as the API presents it.',
} as const

export const EntityResultsSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		results: {
			items: {
				$ref: '#/components/schemas/ResultSummary',
			},
			type: 'array',
			title: 'Results',
		},
	},
	type: 'object',
	required: ['entity', 'results'],
	title: 'EntityResults',
	description: "An entity's results for one or more tests.",
} as const

export const ForcePasswordResetRequestSchema = {
	properties: {
		emails: {
			items: {
				type: 'string',
				format: 'email',
			},
			type: 'array',
			title: 'Emails',
		},
		includeAllActiveUsers: {
			type: 'boolean',
			title: 'Includeallactiveusers',
			default: false,
		},
	},
	type: 'object',
	title: 'ForcePasswordResetRequest',
} as const

export const GradePublicSchema = {
	properties: {
		code: {
			type: 'string',
			title: 'Code',
		},
		label: {
			type: 'string',
			title: 'Label',
		},
		sortOrder: {
			type: 'integer',
			title: 'Sortorder',
		},
		isAggregate: {
			type: 'boolean',
			title: 'Isaggregate',
		},
	},
	type: 'object',
	required: ['code', 'label', 'sortOrder', 'isAggregate'],
	title: 'GradePublic',
} as const

export const GradeReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		testYear: {
			type: 'integer',
			title: 'Testyear',
		},
		testId: {
			type: 'integer',
			title: 'Testid',
		},
		studentGroupId: {
			type: 'integer',
			title: 'Studentgroupid',
		},
		grades: {
			items: {
				$ref: '#/components/schemas/GradeResult',
			},
			type: 'array',
			title: 'Grades',
		},
	},
	type: 'object',
	required: ['entity', 'testYear', 'testId', 'studentGroupId', 'grades'],
	title: 'GradeReport',
} as const

export const GradeResultSchema = {
	properties: {
		grade: {
			type: 'string',
			title: 'Grade',
		},
		label: {
			type: 'string',
			title: 'Label',
		},
		sortOrder: {
			type: 'integer',
			title: 'Sortorder',
		},
		studentsTested: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentstested',
		},
		meanScaleScore: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Meanscalescore',
		},
		metOrAbovePct: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Metorabovepct',
		},
		suppressed: {
			type: 'boolean',
			title: 'Suppressed',
			default: false,
		},
		levels: {
			items: {
				$ref: '#/components/schemas/LevelResult',
			},
			type: 'array',
			title: 'Levels',
		},
	},
	type: 'object',
	required: ['grade', 'label', 'sortOrder', 'levels'],
	title: 'GradeResult',
	description: "One grade's result, for the by-grade report.",
} as const

export const GrowthReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		reportingYear: {
			type: 'integer',
			title: 'Reportingyear',
		},
		studentGroupCode: {
			type: 'string',
			title: 'Studentgroupcode',
		},
		results: {
			items: {
				$ref: '#/components/schemas/GrowthResultPublic',
			},
			type: 'array',
			title: 'Results',
		},
		availableYears: {
			items: {
				type: 'integer',
			},
			type: 'array',
			title: 'Availableyears',
		},
		isInformational: {
			type: 'boolean',
			title: 'Isinformational',
			default: true,
		},
	},
	type: 'object',
	required: ['entity', 'reportingYear', 'studentGroupCode', 'results', 'availableYears'],
	title: 'GrowthReport',
	description:
		'Growth in ELA and mathematics for one entity and year.\n\nGrowth is published for information only: the State Board adopted it in\nJuly 2025 and it is not used for Local Control Funding Formula\neligibility.  ``isInformational`` is always true and clients must say so.',
} as const

export const GrowthResultPublicSchema = {
	properties: {
		subject: {
			type: 'string',
			title: 'Subject',
		},
		denominator: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Denominator',
		},
		growth: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Growth',
		},
		estimateMethod: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Estimatemethod',
		},
		estimateMethodName: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Estimatemethodname',
		},
		performanceCategory: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Performancecategory',
		},
		performanceCategoryName: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Performancecategoryname',
		},
		numberImproved: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Numberimproved',
		},
		percentImproved: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Percentimproved',
		},
	},
	type: 'object',
	required: ['subject'],
	title: 'GrowthResultPublic',
	description: "One subject's growth figure for one entity.",
} as const

export const HTTPValidationErrorSchema = {
	properties: {
		detail: {
			items: {
				$ref: '#/components/schemas/ValidationError',
			},
			type: 'array',
			title: 'Detail',
		},
	},
	type: 'object',
	title: 'HTTPValidationError',
} as const

export const IndicatorGroupReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		reportingYear: {
			type: 'integer',
			title: 'Reportingyear',
		},
		indicatorCode: {
			type: 'string',
			title: 'Indicatorcode',
		},
		indicatorName: {
			type: 'string',
			title: 'Indicatorname',
		},
		allStudents: {
			anyOf: [
				{
					$ref: '#/components/schemas/IndicatorResult',
				},
				{
					type: 'null',
				},
			],
		},
		groups: {
			items: {
				$ref: '#/components/schemas/IndicatorResult',
			},
			type: 'array',
			title: 'Groups',
		},
	},
	type: 'object',
	required: ['entity', 'reportingYear', 'indicatorCode', 'indicatorName', 'groups'],
	title: 'IndicatorGroupReport',
	description: 'One indicator, broken out by student group.',
} as const

export const IndicatorPublicSchema = {
	properties: {
		code: {
			type: 'string',
			title: 'Code',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		shortName: {
			type: 'string',
			title: 'Shortname',
		},
		lowerIsBetter: {
			type: 'boolean',
			title: 'Lowerisbetter',
		},
		unit: {
			type: 'string',
			title: 'Unit',
		},
		sortOrder: {
			type: 'integer',
			title: 'Sortorder',
		},
	},
	type: 'object',
	required: ['code', 'name', 'shortName', 'lowerIsBetter', 'unit', 'sortOrder'],
	title: 'IndicatorPublic',
	description: 'One of the seven state indicators.',
} as const

export const IndicatorReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		reportingYear: {
			type: 'integer',
			title: 'Reportingyear',
		},
		studentGroupCode: {
			type: 'string',
			title: 'Studentgroupcode',
		},
		results: {
			items: {
				$ref: '#/components/schemas/IndicatorResult',
			},
			type: 'array',
			title: 'Results',
		},
		availableYears: {
			items: {
				type: 'integer',
			},
			type: 'array',
			title: 'Availableyears',
		},
		includesProjections: {
			type: 'boolean',
			title: 'Includesprojections',
			default: false,
		},
	},
	type: 'object',
	required: ['entity', 'reportingYear', 'studentGroupCode', 'results', 'availableYears'],
	title: 'IndicatorReport',
	description: 'Every indicator for one entity and year.',
} as const

export const IndicatorResultSchema = {
	properties: {
		indicatorCode: {
			type: 'string',
			title: 'Indicatorcode',
		},
		indicatorName: {
			type: 'string',
			title: 'Indicatorname',
		},
		studentGroupCode: {
			type: 'string',
			title: 'Studentgroupcode',
		},
		variant: {
			type: 'string',
			title: 'Variant',
		},
		currNumerator: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Currnumerator',
		},
		currDenominator: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Currdenominator',
		},
		currStatus: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Currstatus',
		},
		priorStatus: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorstatus',
		},
		change: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Change',
		},
		statusLevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Statuslevel',
		},
		statusLabel: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Statuslabel',
		},
		changeLevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Changelevel',
		},
		changeLabel: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Changelabel',
		},
		color: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Color',
		},
		colorName: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Colorname',
		},
		box: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Box',
		},
		accountabilityMet: {
			type: 'boolean',
			title: 'Accountabilitymet',
			default: false,
		},
		smallDenominator: {
			type: 'boolean',
			title: 'Smalldenominator',
			default: false,
		},
		dassFlag: {
			type: 'boolean',
			title: 'Dassflag',
			default: false,
		},
		isProjected: {
			type: 'boolean',
			title: 'Isprojected',
			default: false,
		},
		projectionBasis: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Projectionbasis',
		},
	},
	type: 'object',
	required: ['indicatorCode', 'indicatorName', 'studentGroupCode', 'variant'],
	title: 'IndicatorResult',
	description: "One indicator's result for one entity.",
} as const

export const IndicatorTrendPointSchema = {
	properties: {
		reportingYear: {
			type: 'integer',
			title: 'Reportingyear',
		},
		currStatus: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Currstatus',
		},
		change: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Change',
		},
		statusLevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Statuslevel',
		},
		changeLevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Changelevel',
		},
		color: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Color',
		},
		colorName: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Colorname',
		},
		isProjected: {
			type: 'boolean',
			title: 'Isprojected',
			default: false,
		},
	},
	type: 'object',
	required: ['reportingYear'],
	title: 'IndicatorTrendPoint',
	description: "One year of an indicator's history.",
} as const

export const IndicatorTrendReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		indicatorCode: {
			type: 'string',
			title: 'Indicatorcode',
		},
		indicatorName: {
			type: 'string',
			title: 'Indicatorname',
		},
		studentGroupCode: {
			type: 'string',
			title: 'Studentgroupcode',
		},
		points: {
			items: {
				$ref: '#/components/schemas/IndicatorTrendPoint',
			},
			type: 'array',
			title: 'Points',
		},
		missingYears: {
			items: {
				type: 'integer',
			},
			type: 'array',
			title: 'Missingyears',
		},
	},
	type: 'object',
	required: [
		'entity',
		'indicatorCode',
		'indicatorName',
		'studentGroupCode',
		'points',
		'missingYears',
	],
	title: 'IndicatorTrendReport',
	description: 'One indicator over time for one entity.',
} as const

export const IngestFilePublicSchema = {
	properties: {
		sourceKey: {
			type: 'string',
			title: 'Sourcekey',
		},
		program: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Program',
		},
		testType: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Testtype',
		},
		testYear: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Testyear',
		},
		status: {
			$ref: '#/components/schemas/IngestStatus',
		},
		resultRows: {
			type: 'integer',
			title: 'Resultrows',
		},
		subscoreRows: {
			type: 'integer',
			title: 'Subscorerows',
		},
		durationSeconds: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Durationseconds',
		},
		error: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Error',
		},
		loadedAt: {
			anyOf: [
				{
					type: 'string',
					format: 'date-time',
				},
				{
					type: 'null',
				},
			],
			title: 'Loadedat',
		},
	},
	type: 'object',
	required: ['sourceKey', 'status', 'resultRows', 'subscoreRows'],
	title: 'IngestFilePublic',
	description: 'The outcome of one file within a run.',
} as const

export const IngestRequestSchema = {
	properties: {
		sourceUri: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Sourceuri',
		},
		force: {
			type: 'boolean',
			title: 'Force',
			default: false,
		},
		only: {
			anyOf: [
				{
					items: {
						type: 'string',
					},
					type: 'array',
				},
				{
					type: 'null',
				},
			],
			title: 'Only',
		},
		years: {
			anyOf: [
				{
					items: {
						type: 'integer',
					},
					type: 'array',
				},
				{
					type: 'null',
				},
			],
			title: 'Years',
		},
	},
	type: 'object',
	title: 'IngestRequest',
	description: 'What to import.',
} as const

export const IngestRunDetailSchema = {
	properties: {
		run: {
			$ref: '#/components/schemas/IngestRunPublic',
		},
		files: {
			items: {
				$ref: '#/components/schemas/IngestFilePublic',
			},
			type: 'array',
			title: 'Files',
		},
	},
	type: 'object',
	required: ['run', 'files'],
	title: 'IngestRunDetail',
	description: 'A run together with every file it touched.',
} as const

export const IngestRunListSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/IngestRunPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'IngestRunList',
	description: 'A page of import runs.',
} as const

export const IngestRunPublicSchema = {
	properties: {
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		sourceUri: {
			type: 'string',
			title: 'Sourceuri',
		},
		status: {
			$ref: '#/components/schemas/IngestStatus',
		},
		startedAt: {
			type: 'string',
			format: 'date-time',
			title: 'Startedat',
		},
		finishedAt: {
			anyOf: [
				{
					type: 'string',
					format: 'date-time',
				},
				{
					type: 'null',
				},
			],
			title: 'Finishedat',
		},
		filesSeen: {
			type: 'integer',
			title: 'Filesseen',
		},
		filesLoaded: {
			type: 'integer',
			title: 'Filesloaded',
		},
		filesSkipped: {
			type: 'integer',
			title: 'Filesskipped',
		},
		resultRows: {
			type: 'integer',
			title: 'Resultrows',
		},
		subscoreRows: {
			type: 'integer',
			title: 'Subscorerows',
		},
		error: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Error',
		},
	},
	type: 'object',
	required: [
		'id',
		'sourceUri',
		'status',
		'startedAt',
		'filesSeen',
		'filesLoaded',
		'filesSkipped',
		'resultRows',
		'subscoreRows',
	],
	title: 'IngestRunPublic',
	description: 'One import run.',
} as const

export const IngestStatusSchema = {
	type: 'string',
	enum: ['running', 'succeeded', 'failed', 'skipped'],
	title: 'IngestStatus',
	description: 'Lifecycle of an ingest run or of one file within it.',
} as const

export const ItemCreateSchema = {
	properties: {
		title: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
	},
	type: 'object',
	required: ['title'],
	title: 'ItemCreate',
} as const

export const ItemPublicSchema = {
	properties: {
		title: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		ownerId: {
			type: 'string',
			format: 'uuid',
			title: 'Ownerid',
		},
		createdAt: {
			anyOf: [
				{
					type: 'string',
					format: 'date-time',
				},
				{
					type: 'null',
				},
			],
			title: 'Createdat',
		},
	},
	type: 'object',
	required: ['title', 'id', 'ownerId'],
	title: 'ItemPublic',
} as const

export const ItemUpdateSchema = {
	properties: {
		title: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					minLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
	},
	type: 'object',
	title: 'ItemUpdate',
} as const

export const ItemsPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/ItemPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'ItemsPublic',
} as const

export const LevelPublicSchema = {
	properties: {
		levelNumber: {
			type: 'integer',
			title: 'Levelnumber',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		shortName: {
			type: 'string',
			title: 'Shortname',
		},
		description: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
	},
	type: 'object',
	required: ['levelNumber', 'name', 'shortName'],
	title: 'LevelPublic',
	description: 'One achievement level of a scheme.',
} as const

export const LevelResultSchema = {
	properties: {
		levelNumber: {
			type: 'integer',
			title: 'Levelnumber',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		shortName: {
			type: 'string',
			title: 'Shortname',
		},
		count: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Count',
		},
		pct: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Pct',
		},
	},
	type: 'object',
	required: ['levelNumber', 'name', 'shortName'],
	title: 'LevelResult',
	description: 'A labelled slice of a distribution.',
} as const

export const LevelSchemePublicSchema = {
	properties: {
		code: {
			type: 'string',
			title: 'Code',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		levelCount: {
			type: 'integer',
			title: 'Levelcount',
		},
		proficientFromLevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Proficientfromlevel',
		},
		description: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
		levels: {
			items: {
				$ref: '#/components/schemas/LevelPublic',
			},
			type: 'array',
			title: 'Levels',
		},
	},
	type: 'object',
	required: ['code', 'name', 'levelCount', 'levels'],
	title: 'LevelSchemePublic',
} as const

export const LocalIndicatorCatalogSchema = {
	properties: {
		reportingYear: {
			type: 'integer',
			title: 'Reportingyear',
		},
		years: {
			items: {
				type: 'integer',
			},
			type: 'array',
			title: 'Years',
		},
		priorities: {
			items: {
				$ref: '#/components/schemas/PriorityPublic',
			},
			type: 'array',
			title: 'Priorities',
		},
		performanceValues: {
			items: {
				type: 'string',
			},
			type: 'array',
			title: 'Performancevalues',
		},
	},
	type: 'object',
	required: ['reportingYear', 'years', 'priorities', 'performanceValues'],
	title: 'LocalIndicatorCatalog',
	description: 'Everything needed to populate the local indicator filters.',
} as const

export const LocalIndicatorDetailSchema = {
	properties: {
		priorityNumber: {
			type: 'integer',
			title: 'Prioritynumber',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		shortName: {
			type: 'string',
			title: 'Shortname',
		},
		description: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
		countyOfficeOnly: {
			type: 'boolean',
			title: 'Countyofficeonly',
			default: false,
		},
		performance: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Performance',
		},
		meetingDate: {
			anyOf: [
				{
					type: 'string',
					format: 'date',
				},
				{
					type: 'null',
				},
			],
			title: 'Meetingdate',
		},
		additionalInfo: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Additionalinfo',
		},
		ratings: {
			additionalProperties: {
				type: 'integer',
			},
			type: 'object',
			title: 'Ratings',
			default: {},
		},
		narratives: {
			items: {
				additionalProperties: {
					type: 'string',
				},
				type: 'object',
			},
			type: 'array',
			title: 'Narratives',
			default: [],
		},
	},
	type: 'object',
	required: ['priorityNumber', 'name', 'shortName'],
	title: 'LocalIndicatorDetail',
	description: 'One priority in full, including everything the LEA wrote.',
} as const

export const LocalIndicatorReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		reportedBy: {
			$ref: '#/components/schemas/EntityPublic',
		},
		reportingYear: {
			type: 'integer',
			title: 'Reportingyear',
		},
		priorities: {
			items: {
				$ref: '#/components/schemas/LocalIndicatorSummary',
			},
			type: 'array',
			title: 'Priorities',
		},
		availableYears: {
			items: {
				type: 'integer',
			},
			type: 'array',
			title: 'Availableyears',
		},
	},
	type: 'object',
	required: ['entity', 'reportedBy', 'reportingYear', 'priorities', 'availableYears'],
	title: 'LocalIndicatorReport',
	description: 'Every priority for one LEA and year.',
} as const

export const LocalIndicatorSummarySchema = {
	properties: {
		priorityNumber: {
			type: 'integer',
			title: 'Prioritynumber',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		shortName: {
			type: 'string',
			title: 'Shortname',
		},
		countyOfficeOnly: {
			type: 'boolean',
			title: 'Countyofficeonly',
			default: false,
		},
		performance: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Performance',
		},
		meetingDate: {
			anyOf: [
				{
					type: 'string',
					format: 'date',
				},
				{
					type: 'null',
				},
			],
			title: 'Meetingdate',
		},
		responseCount: {
			type: 'integer',
			title: 'Responsecount',
			default: 0,
		},
		hasNarrative: {
			type: 'boolean',
			title: 'Hasnarrative',
			default: false,
		},
	},
	type: 'object',
	required: ['priorityNumber', 'name', 'shortName'],
	title: 'LocalIndicatorSummary',
	description: "One priority's headline result for one LEA.",
} as const

export const LocalIndicatorTrendPointSchema = {
	properties: {
		reportingYear: {
			type: 'integer',
			title: 'Reportingyear',
		},
		performance: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Performance',
		},
		meetingDate: {
			anyOf: [
				{
					type: 'string',
					format: 'date',
				},
				{
					type: 'null',
				},
			],
			title: 'Meetingdate',
		},
	},
	type: 'object',
	required: ['reportingYear'],
	title: 'LocalIndicatorTrendPoint',
} as const

export const LocalIndicatorTrendReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		reportedBy: {
			$ref: '#/components/schemas/EntityPublic',
		},
		priorityNumber: {
			type: 'integer',
			title: 'Prioritynumber',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		points: {
			items: {
				$ref: '#/components/schemas/LocalIndicatorTrendPoint',
			},
			type: 'array',
			title: 'Points',
		},
	},
	type: 'object',
	required: ['entity', 'reportedBy', 'priorityNumber', 'name', 'points'],
	title: 'LocalIndicatorTrendReport',
	description: 'One priority across every year the LEA has reported.',
} as const

export const MessageSchema = {
	properties: {
		message: {
			type: 'string',
			title: 'Message',
		},
		success: {
			type: 'boolean',
			title: 'Success',
			default: true,
		},
		status: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Status',
		},
		code: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Code',
		},
	},
	type: 'object',
	required: ['message'],
	title: 'Message',
	description: 'A message for an API response.',
} as const

export const MetOrAboveSourceSchema = {
	type: 'string',
	enum: ['published', 'derived'],
	title: 'MetOrAboveSource',
	description: 'Where the "met or above" figure on a result row came from.',
} as const

export const NewPasswordSchema = {
	properties: {
		token: {
			type: 'string',
			title: 'Token',
		},
		newPassword: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Newpassword',
		},
	},
	type: 'object',
	required: ['token', 'newPassword'],
	title: 'NewPassword',
} as const

export const OverviewReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		testYear: {
			type: 'integer',
			title: 'Testyear',
		},
		studentGroupId: {
			type: 'integer',
			title: 'Studentgroupid',
		},
		grade: {
			type: 'string',
			title: 'Grade',
		},
		schoolType: {
			type: 'string',
			title: 'Schooltype',
		},
		results: {
			items: {
				$ref: '#/components/schemas/ResultSummary',
			},
			type: 'array',
			title: 'Results',
		},
		comparisons: {
			items: {
				$ref: '#/components/schemas/EntityResults',
			},
			type: 'array',
			title: 'Comparisons',
		},
	},
	type: 'object',
	required: [
		'entity',
		'testYear',
		'studentGroupId',
		'grade',
		'schoolType',
		'results',
		'comparisons',
	],
	title: 'OverviewReport',
	description: 'The equivalent of the state\'s "Test Results" landing report.',
} as const

export const PriorityPublicSchema = {
	properties: {
		priorityNumber: {
			type: 'integer',
			title: 'Prioritynumber',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		shortName: {
			type: 'string',
			title: 'Shortname',
		},
		description: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
		countyOfficeOnly: {
			type: 'boolean',
			title: 'Countyofficeonly',
			default: false,
		},
		sortOrder: {
			type: 'integer',
			title: 'Sortorder',
			default: 0,
		},
	},
	type: 'object',
	required: ['priorityNumber', 'name', 'shortName'],
	title: 'PriorityPublic',
	description: 'One of the seven LCFF priorities reported as a local indicator.',
} as const

export const PrivateUserCreateSchema = {
	properties: {
		email: {
			type: 'string',
			title: 'Email',
		},
		password: {
			type: 'string',
			title: 'Password',
		},
		full_name: {
			type: 'string',
			title: 'Full Name',
		},
		is_verified: {
			type: 'boolean',
			title: 'Is Verified',
			default: false,
		},
	},
	type: 'object',
	required: ['email', 'password', 'full_name'],
	title: 'PrivateUserCreate',
} as const

export const ProgramSchema = {
	type: 'string',
	enum: ['CAASPP', 'ELPAC'],
	title: 'Program',
	description: "The two assessment programs reported by the state's public site.",
} as const

export const ResultSummarySchema = {
	properties: {
		testId: {
			type: 'integer',
			title: 'Testid',
		},
		testCode: {
			type: 'string',
			title: 'Testcode',
		},
		testName: {
			type: 'string',
			title: 'Testname',
		},
		shortName: {
			type: 'string',
			title: 'Shortname',
		},
		program: {
			$ref: '#/components/schemas/Program',
		},
		subject: {
			type: 'string',
			title: 'Subject',
		},
		grade: {
			type: 'string',
			title: 'Grade',
		},
		studentsEnrolled: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentsenrolled',
		},
		studentsTested: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentstested',
		},
		studentsTestedWithScores: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentstestedwithscores',
		},
		participationRate: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Participationrate',
		},
		meanScaleScore: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Meanscalescore',
		},
		metOrAboveCount: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Metorabovecount',
		},
		metOrAbovePct: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Metorabovepct',
		},
		metOrAboveSource: {
			anyOf: [
				{
					$ref: '#/components/schemas/MetOrAboveSource',
				},
				{
					type: 'null',
				},
			],
		},
		overallTotal: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Overalltotal',
		},
		suppressed: {
			type: 'boolean',
			title: 'Suppressed',
			default: false,
		},
		levelSchemeCode: {
			type: 'string',
			title: 'Levelschemecode',
		},
		levels: {
			items: {
				$ref: '#/components/schemas/LevelResult',
			},
			type: 'array',
			title: 'Levels',
		},
		derivedFromChildren: {
			type: 'boolean',
			title: 'Derivedfromchildren',
			default: false,
		},
	},
	type: 'object',
	required: [
		'testId',
		'testCode',
		'testName',
		'shortName',
		'program',
		'subject',
		'grade',
		'levelSchemeCode',
		'levels',
	],
	title: 'ResultSummary',
	description:
		'One test\'s overall result for the requested cell.\n\n``suppressed`` means the state withheld the figures because too few\nstudents were tested.  Values can also be absent without suppression: the\nmean scale score is not reported for the "all grades" aggregate, because\nscale scores are not comparable between grades.',
} as const

export const SchoolPublicSchema = {
	properties: {
		cdsCode: {
			type: 'string',
			maxLength: 255,
			title: 'Cdscode',
		},
		ncesDist: {
			type: 'string',
			maxLength: 255,
			title: 'Ncesdist',
		},
		ncesSchool: {
			type: 'string',
			maxLength: 255,
			title: 'Ncesschool',
		},
		schoolCode: {
			type: 'string',
			maxLength: 255,
			title: 'Schoolcode',
		},
		statusType: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Statustype',
		},
		county: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'County',
		},
		district: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'District',
		},
		school: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'School',
		},
		street: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Street',
		},
		streetAbr: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Streetabr',
		},
		city: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'City',
		},
		zip: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Zip',
		},
		state: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'State',
		},
		mailStreet: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Mailstreet',
		},
		mailStreetAbr: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Mailstreetabr',
		},
		mailCity: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Mailcity',
		},
		mailZip: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Mailzip',
		},
		mailState: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Mailstate',
		},
		phone: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Phone',
		},
		ext: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Ext',
		},
		faxNumber: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Faxnumber',
		},
		website: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Website',
		},
		openDate: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Opendate',
		},
		closedDate: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Closeddate',
		},
		charter: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Charter',
		},
		charterNum: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Charternum',
		},
		fundingType: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fundingtype',
		},
		doc: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Doc',
		},
		docType: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Doctype',
		},
		soc: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Soc',
		},
		socType: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Soctype',
		},
		edopsCode: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Edopscode',
		},
		edopsName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Edopsname',
		},
		eilCode: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Eilcode',
		},
		eilName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Eilname',
		},
		gsOffered: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Gsoffered',
		},
		gsServed: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Gsserved',
		},
		virtual: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Virtual',
		},
		magnet: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Magnet',
		},
		yearRoundYn: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Yearroundyn',
		},
		federalDfcDistrictId: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Federaldfcdistrictid',
		},
		latitude: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Latitude',
		},
		longitude: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Longitude',
		},
		admFname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Admfname',
		},
		admLname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Admlname',
		},
		lastUpDate: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Lastupdate',
		},
		multilingual: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Multilingual',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
	},
	type: 'object',
	required: ['cdsCode', 'ncesDist', 'ncesSchool', 'schoolCode', 'id'],
	title: 'SchoolPublic',
} as const

export const SchoolSummarySchema = {
	properties: {
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		school: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'School',
		},
		city: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'City',
		},
		county: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'County',
		},
		cdsCode: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Cdscode',
		},
		schoolCode: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Schoolcode',
		},
	},
	type: 'object',
	required: ['id'],
	title: 'SchoolSummary',
} as const

export const SchoolTypeSchema = {
	type: 'string',
	enum: ['all', 'charter', 'non-charter'],
	title: 'SchoolType',
	description: "The state's charter filter on aggregate reports.",
} as const

export const SchoolsPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/SchoolPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'SchoolsPublic',
} as const

export const SchoolsSummarySchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/SchoolSummary',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'SchoolsSummary',
} as const

export const StudentGroupCodePublicSchema = {
	properties: {
		code: {
			type: 'string',
			title: 'Code',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
	},
	type: 'object',
	required: ['code', 'name'],
	title: 'StudentGroupCodePublic',
	description:
		"A Dashboard student group.\n\nThese are the state's short codes, which are not the numeric CAASPP and\nELPAC group ids used by the assessment reports.",
} as const

export const StudentGroupPublicSchema = {
	properties: {
		program: {
			$ref: '#/components/schemas/Program',
		},
		studentGroupId: {
			type: 'integer',
			title: 'Studentgroupid',
		},
		code: {
			type: 'string',
			title: 'Code',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		category: {
			type: 'string',
			title: 'Category',
		},
		sortOrder: {
			type: 'integer',
			title: 'Sortorder',
		},
	},
	type: 'object',
	required: ['program', 'studentGroupId', 'code', 'name', 'category', 'sortOrder'],
	title: 'StudentGroupPublic',
} as const

export const StudentGroupReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		testYear: {
			type: 'integer',
			title: 'Testyear',
		},
		testId: {
			type: 'integer',
			title: 'Testid',
		},
		grade: {
			type: 'string',
			title: 'Grade',
		},
		allStudents: {
			anyOf: [
				{
					$ref: '#/components/schemas/StudentGroupResult',
				},
				{
					type: 'null',
				},
			],
		},
		groups: {
			items: {
				$ref: '#/components/schemas/StudentGroupResult',
			},
			type: 'array',
			title: 'Groups',
		},
	},
	type: 'object',
	required: ['entity', 'testYear', 'testId', 'grade', 'groups'],
	title: 'StudentGroupReport',
} as const

export const StudentGroupResultSchema = {
	properties: {
		studentGroupId: {
			type: 'integer',
			title: 'Studentgroupid',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		category: {
			type: 'string',
			title: 'Category',
		},
		sortOrder: {
			type: 'integer',
			title: 'Sortorder',
		},
		studentsEnrolled: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentsenrolled',
		},
		studentsTested: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentstested',
		},
		meanScaleScore: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Meanscalescore',
		},
		metOrAbovePct: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Metorabovepct',
		},
		suppressed: {
			type: 'boolean',
			title: 'Suppressed',
			default: false,
		},
		levels: {
			items: {
				$ref: '#/components/schemas/LevelResult',
			},
			type: 'array',
			title: 'Levels',
		},
	},
	type: 'object',
	required: ['studentGroupId', 'name', 'category', 'sortOrder', 'levels'],
	title: 'StudentGroupResult',
	description: "One student group's result, for the student group comparison report.",
} as const

export const SubscoreKindSchema = {
	type: 'string',
	enum: ['area', 'composite_area', 'domain', 'composite'],
	title: 'SubscoreKind',
	description:
		'Kind of reported subscore.\n\n``AREA`` and ``COMPOSITE_AREA`` are Smarter Balanced claim reporting\ncategories; ``DOMAIN`` is used by CAST, CSA and ELPAC; ``COMPOSITE`` is an\nELPAC/CSA composite that carries its own mean scale score.',
} as const

export const SubscorePublicSchema = {
	properties: {
		code: {
			type: 'string',
			title: 'Code',
		},
		kind: {
			$ref: '#/components/schemas/SubscoreKind',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		reportsMeanScaleScore: {
			type: 'boolean',
			title: 'Reportsmeanscalescore',
		},
		bandScheme: {
			$ref: '#/components/schemas/LevelSchemePublic',
		},
		sortOrder: {
			type: 'integer',
			title: 'Sortorder',
		},
	},
	type: 'object',
	required: ['code', 'kind', 'name', 'reportsMeanScaleScore', 'bandScheme', 'sortOrder'],
	title: 'SubscorePublic',
	description: 'An area, domain or composite a test reports in a given year.',
} as const

export const SubscoreReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		testYear: {
			type: 'integer',
			title: 'Testyear',
		},
		testId: {
			type: 'integer',
			title: 'Testid',
		},
		studentGroupId: {
			type: 'integer',
			title: 'Studentgroupid',
		},
		grade: {
			type: 'string',
			title: 'Grade',
		},
		subscores: {
			items: {
				$ref: '#/components/schemas/SubscoreResult',
			},
			type: 'array',
			title: 'Subscores',
		},
	},
	type: 'object',
	required: ['entity', 'testYear', 'testId', 'studentGroupId', 'grade', 'subscores'],
	title: 'SubscoreReport',
} as const

export const SubscoreResultSchema = {
	properties: {
		code: {
			type: 'string',
			title: 'Code',
		},
		kind: {
			$ref: '#/components/schemas/SubscoreKind',
		},
		name: {
			type: 'string',
			title: 'Name',
		},
		sortOrder: {
			type: 'integer',
			title: 'Sortorder',
		},
		meanScaleScore: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Meanscalescore',
		},
		total: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Total',
		},
		bandSchemeCode: {
			type: 'string',
			title: 'Bandschemecode',
		},
		bands: {
			items: {
				$ref: '#/components/schemas/LevelResult',
			},
			type: 'array',
			title: 'Bands',
		},
	},
	type: 'object',
	required: ['code', 'kind', 'name', 'sortOrder', 'bandSchemeCode', 'bands'],
	title: 'SubscoreResult',
	description: 'One area, domain or composite for the requested cell.',
} as const

export const TokenSchema = {
	properties: {
		access_token: {
			type: 'string',
			title: 'Access Token',
		},
		token_type: {
			type: 'string',
			title: 'Token Type',
			default: 'bearer',
		},
	},
	type: 'object',
	required: ['access_token'],
	title: 'Token',
	description:
		'A JSON payload containing the access token. The names follow the JWT spec (RFC 7519).',
} as const

export const TrendPointSchema = {
	properties: {
		testYear: {
			type: 'integer',
			title: 'Testyear',
		},
		studentsTested: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentstested',
		},
		meanScaleScore: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Meanscalescore',
		},
		metOrAbovePct: {
			anyOf: [
				{
					type: 'string',
					pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
				},
				{
					type: 'null',
				},
			],
			title: 'Metorabovepct',
		},
		suppressed: {
			type: 'boolean',
			title: 'Suppressed',
			default: false,
		},
		levels: {
			items: {
				$ref: '#/components/schemas/LevelResult',
			},
			type: 'array',
			title: 'Levels',
		},
	},
	type: 'object',
	required: ['testYear', 'levels'],
	title: 'TrendPoint',
	description: 'One year of a change-over-time series.',
} as const

export const TrendReportSchema = {
	properties: {
		entity: {
			$ref: '#/components/schemas/EntityPublic',
		},
		testId: {
			type: 'integer',
			title: 'Testid',
		},
		studentGroupId: {
			type: 'integer',
			title: 'Studentgroupid',
		},
		grade: {
			type: 'string',
			title: 'Grade',
		},
		points: {
			items: {
				$ref: '#/components/schemas/TrendPoint',
			},
			type: 'array',
			title: 'Points',
		},
		scaleBreakNote: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Scalebreaknote',
		},
	},
	type: 'object',
	required: ['entity', 'testId', 'studentGroupId', 'grade', 'points'],
	title: 'TrendReport',
} as const

export const UpdatePasswordSchema = {
	properties: {
		currentPassword: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Currentpassword',
		},
		newPassword: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Newpassword',
		},
	},
	type: 'object',
	required: ['currentPassword', 'newPassword'],
	title: 'UpdatePassword',
} as const

export const UserCreateSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		isActive: {
			type: 'boolean',
			title: 'Isactive',
			default: true,
		},
		isSuperuser: {
			type: 'boolean',
			title: 'Issuperuser',
			default: false,
		},
		fullName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fullname',
		},
		password: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Password',
		},
	},
	type: 'object',
	required: ['email', 'password'],
	title: 'UserCreate',
} as const

export const UserPreferencesUpdateSchema = {
	properties: {
		lastViewedCds: {
			anyOf: [
				{
					type: 'string',
					maxLength: 14,
				},
				{
					type: 'null',
				},
			],
			title: 'Lastviewedcds',
		},
	},
	type: 'object',
	title: 'UserPreferencesUpdate',
} as const

export const UserPublicSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		isActive: {
			type: 'boolean',
			title: 'Isactive',
			default: true,
		},
		isSuperuser: {
			type: 'boolean',
			title: 'Issuperuser',
			default: false,
		},
		fullName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fullname',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		createdAt: {
			anyOf: [
				{
					type: 'string',
					format: 'date-time',
				},
				{
					type: 'null',
				},
			],
			title: 'Createdat',
		},
		forcePasswordReset: {
			type: 'boolean',
			title: 'Forcepasswordreset',
			default: false,
		},
	},
	type: 'object',
	required: ['email', 'id'],
	title: 'UserPublic',
} as const

export const UserRegisterSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		password: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Password',
		},
		fullName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fullname',
		},
	},
	type: 'object',
	required: ['email', 'password'],
	title: 'UserRegister',
} as const

export const UserUpdateSchema = {
	properties: {
		email: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					format: 'email',
				},
				{
					type: 'null',
				},
			],
			title: 'Email',
		},
		isActive: {
			type: 'boolean',
			title: 'Isactive',
			default: true,
		},
		isSuperuser: {
			type: 'boolean',
			title: 'Issuperuser',
			default: false,
		},
		fullName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fullname',
		},
		password: {
			anyOf: [
				{
					type: 'string',
					maxLength: 128,
					minLength: 8,
				},
				{
					type: 'null',
				},
			],
			title: 'Password',
		},
		forcePasswordReset: {
			anyOf: [
				{
					type: 'boolean',
				},
				{
					type: 'null',
				},
			],
			title: 'Forcepasswordreset',
		},
	},
	type: 'object',
	title: 'UserUpdate',
} as const

export const UserUpdateMeSchema = {
	properties: {
		fullName: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fullname',
		},
		email: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					format: 'email',
				},
				{
					type: 'null',
				},
			],
			title: 'Email',
		},
		lastViewedCds: {
			anyOf: [
				{
					type: 'string',
					maxLength: 14,
				},
				{
					type: 'null',
				},
			],
			title: 'Lastviewedcds',
		},
	},
	type: 'object',
	title: 'UserUpdateMe',
} as const

export const UsersPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/UserPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'UsersPublic',
} as const

export const ValidationErrorSchema = {
	properties: {
		loc: {
			items: {
				anyOf: [
					{
						type: 'string',
					},
					{
						type: 'integer',
					},
				],
			},
			type: 'array',
			title: 'Location',
		},
		msg: {
			type: 'string',
			title: 'Message',
		},
		type: {
			type: 'string',
			title: 'Error Type',
		},
		input: {
			title: 'Input',
		},
		ctx: {
			type: 'object',
			title: 'Context',
		},
	},
	type: 'object',
	required: ['loc', 'msg', 'type'],
	title: 'ValidationError',
} as const
