// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: `${string}://${string}` | (string & {})
}

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
	/**
	 * Grant Type
	 */
	grant_type?: string | null
	/**
	 * Username
	 */
	username: string
	/**
	 * Password
	 */
	password: string
	/**
	 * Scope
	 */
	scope?: string
	/**
	 * Client Id
	 */
	client_id?: string | null
	/**
	 * Client Secret
	 */
	client_secret?: string | null
}

/**
 * CensusData
 */
export type CensusData = {
	/**
	 * Academicyear
	 */
	academicYear: number
	/**
	 * Aggregationlevel
	 */
	aggregationLevel: string
	/**
	 * Cdscode
	 */
	cdsCode: string
	/**
	 * Charter
	 */
	charter?: string | null
	/**
	 * Reportingcategory
	 */
	reportingCategory: string
	/**
	 * Totalenr
	 */
	totalEnr?: number
	/**
	 * Grtk
	 */
	grTk?: number
	/**
	 * Grkn
	 */
	grKn?: number
	/**
	 * Gr1
	 */
	gr1?: number
	/**
	 * Gr2
	 */
	gr2?: number
	/**
	 * Gr3
	 */
	gr3?: number
	/**
	 * Gr4
	 */
	gr4?: number
	/**
	 * Gr5
	 */
	gr5?: number
	/**
	 * Gr6
	 */
	gr6?: number
	/**
	 * Gr7
	 */
	gr7?: number
	/**
	 * Gr8
	 */
	gr8?: number
	/**
	 * Gr9
	 */
	gr9?: number
	/**
	 * Gr10
	 */
	gr10?: number
	/**
	 * Gr11
	 */
	gr11?: number
	/**
	 * Gr12
	 */
	gr12?: number
	/**
	 * Id
	 */
	id?: string
}

/**
 * DashboardSummaryResponse
 *
 * Response containing multiple tests for a school/district/county.
 */
export type DashboardSummaryResponse = {
	/**
	 * Cds
	 */
	cds: string
	/**
	 * Testyear
	 */
	testYear: string
	/**
	 * Indicators
	 */
	indicators: Array<IndicatorSummary>
}

/**
 * EquityGroupSummary
 *
 * Summary of a student group for the equity report.
 */
export type EquityGroupSummary = {
	/**
	 * Studentgroup
	 */
	studentGroup: string
	/**
	 * Overallmetandabovepct
	 */
	overallMetAndAbovePct?: string | null
	/**
	 * Studentstested
	 */
	studentsTested?: string | null
}

/**
 * EquityReportResponse
 *
 * Response containing student group breakdown for a test.
 */
export type EquityReportResponse = {
	/**
	 * Cds
	 */
	cds: string
	/**
	 * Testid
	 */
	testId: string
	/**
	 * Testyear
	 */
	testYear: string
	/**
	 * Groups
	 */
	groups: Array<EquityGroupSummary>
}

/**
 * ForcePasswordResetRequest
 */
export type ForcePasswordResetRequest = {
	/**
	 * Emails
	 */
	emails?: Array<string>
	/**
	 * Includeallactiveusers
	 */
	includeAllActiveUsers?: boolean
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>
}

/**
 * IndicatorSummary
 *
 * Summary of a specific CAASPP/ELPAC test result.
 */
export type IndicatorSummary = {
	/**
	 * Testid
	 */
	testId: string
	/**
	 * Testtype
	 */
	testType: string
	/**
	 * Grade
	 */
	grade: string
	/**
	 * Studentsenrolled
	 */
	studentsEnrolled: string
	/**
	 * Studentstested
	 */
	studentsTested: string
	/**
	 * Overallmeanscalescore
	 */
	overallMeanScaleScore?: string | null
	/**
	 * Overallmetandabovepct
	 */
	overallMetAndAbovePct?: string | null
	/**
	 * Levels
	 */
	levels?: {
		[key: string]: number
	} | null
}

/**
 * ItemCreate
 *
 * Properties to receive on item creation
 */
export type ItemCreate = {
	/**
	 * Title
	 */
	title: string
	/**
	 * Description
	 */
	description?: string | null
}

/**
 * ItemPublic
 *
 * Properties to return via API, id is always required
 */
export type ItemPublic = {
	/**
	 * Title
	 */
	title: string
	/**
	 * Description
	 */
	description?: string | null
	/**
	 * Id
	 */
	id: string
	/**
	 * Ownerid
	 */
	ownerId: string
	/**
	 * Createdat
	 */
	createdAt?: string | null
}

/**
 * ItemUpdate
 *
 * Properties to receive on item update
 */
export type ItemUpdate = {
	/**
	 * Title
	 */
	title?: string | null
	/**
	 * Description
	 */
	description?: string | null
}

/**
 * ItemsPublic
 */
export type ItemsPublic = {
	/**
	 * Data
	 */
	data: Array<ItemPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * Message
 *
 * Generic message
 */
export type Message = {
	/**
	 * Message
	 */
	message: string
}

/**
 * NewPassword
 */
export type NewPassword = {
	/**
	 * Token
	 */
	token: string
	/**
	 * Newpassword
	 */
	newPassword: string
}

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Password
	 */
	password: string
	/**
	 * Full Name
	 */
	full_name: string
	/**
	 * Is Verified
	 */
	is_verified?: boolean
}

/**
 * SchoolPublic
 */
export type SchoolPublic = {
	/**
	 * Cdscode
	 */
	cdsCode: string
	/**
	 * Ncesdist
	 */
	ncesDist: string
	/**
	 * Ncesschool
	 */
	ncesSchool: string
	/**
	 * Schoolcode
	 */
	schoolCode: string
	/**
	 * Statustype
	 */
	statusType?: string | null
	/**
	 * County
	 */
	county?: string | null
	/**
	 * District
	 */
	district?: string | null
	/**
	 * School
	 */
	school?: string | null
	/**
	 * Street
	 */
	street?: string | null
	/**
	 * Streetabr
	 */
	streetAbr?: string | null
	/**
	 * City
	 */
	city?: string | null
	/**
	 * Zip
	 */
	zip?: string | null
	/**
	 * State
	 */
	state?: string | null
	/**
	 * Mailstreet
	 */
	mailStreet?: string | null
	/**
	 * Mailstreetabr
	 */
	mailStreetAbr?: string | null
	/**
	 * Mailcity
	 */
	mailCity?: string | null
	/**
	 * Mailzip
	 */
	mailZip?: string | null
	/**
	 * Mailstate
	 */
	mailState?: string | null
	/**
	 * Phone
	 */
	phone?: string | null
	/**
	 * Ext
	 */
	ext?: string | null
	/**
	 * Faxnumber
	 */
	faxNumber?: string | null
	/**
	 * Website
	 */
	website?: string | null
	/**
	 * Opendate
	 */
	openDate?: string | null
	/**
	 * Closeddate
	 */
	closedDate?: string | null
	/**
	 * Charter
	 */
	charter?: string | null
	/**
	 * Charternum
	 */
	charterNum?: string | null
	/**
	 * Fundingtype
	 */
	fundingType?: string | null
	/**
	 * Doc
	 */
	doc?: string | null
	/**
	 * Doctype
	 */
	docType?: string | null
	/**
	 * Soc
	 */
	soc?: string | null
	/**
	 * Soctype
	 */
	socType?: string | null
	/**
	 * Edopscode
	 */
	edopsCode?: string | null
	/**
	 * Edopsname
	 */
	edopsName?: string | null
	/**
	 * Eilcode
	 */
	eilCode?: string | null
	/**
	 * Eilname
	 */
	eilName?: string | null
	/**
	 * Gsoffered
	 */
	gsOffered?: string | null
	/**
	 * Gsserved
	 */
	gsServed?: string | null
	/**
	 * Virtual
	 */
	virtual?: string | null
	/**
	 * Magnet
	 */
	magnet?: string | null
	/**
	 * Yearroundyn
	 */
	yearRoundYn?: string | null
	/**
	 * Federaldfcdistrictid
	 */
	federalDfcDistrictId?: string | null
	/**
	 * Latitude
	 */
	latitude?: number | null
	/**
	 * Longitude
	 */
	longitude?: number | null
	/**
	 * Admfname
	 */
	admFname?: string | null
	/**
	 * Admlname
	 */
	admLname?: string | null
	/**
	 * Lastupdate
	 */
	lastUpDate?: string | null
	/**
	 * Multilingual
	 */
	multilingual?: string | null
	/**
	 * Id
	 */
	id: string
}

/**
 * SchoolSummary
 */
export type SchoolSummary = {
	/**
	 * Id
	 */
	id: string
	/**
	 * School
	 */
	school?: string | null
	/**
	 * City
	 */
	city?: string | null
	/**
	 * County
	 */
	county?: string | null
	/**
	 * Cdscode
	 */
	cdsCode?: string | null
	/**
	 * Schoolcode
	 */
	schoolCode?: string | null
}

/**
 * SchoolsPublic
 */
export type SchoolsPublic = {
	/**
	 * Data
	 */
	data: Array<SchoolPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * SchoolsSummary
 */
export type SchoolsSummary = {
	/**
	 * Data
	 */
	data: Array<SchoolSummary>
	/**
	 * Count
	 */
	count: number
}

/**
 * Token
 *
 * A JSON payload containing the access token.
 */
export type Token = {
	/**
	 * Accesstoken
	 */
	accessToken: string
	/**
	 * Tokentype
	 */
	tokenType?: string
}

/**
 * UpdatePassword
 */
export type UpdatePassword = {
	/**
	 * Currentpassword
	 */
	currentPassword: string
	/**
	 * Newpassword
	 */
	newPassword: string
}

/**
 * UserCreate
 */
export type UserCreate = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Isactive
	 */
	isActive?: boolean
	/**
	 * Issuperuser
	 */
	isSuperuser?: boolean
	/**
	 * Fullname
	 */
	fullName?: string | null
	/**
	 * Password
	 */
	password: string
}

/**
 * UserPreferencesUpdate
 */
export type UserPreferencesUpdate = {
	/**
	 * Lastviewedcds
	 */
	lastViewedCds?: string | null
}

/**
 * UserPublic
 */
export type UserPublic = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Isactive
	 */
	isActive?: boolean
	/**
	 * Issuperuser
	 */
	isSuperuser?: boolean
	/**
	 * Fullname
	 */
	fullName?: string | null
	/**
	 * Id
	 */
	id: string
	/**
	 * Createdat
	 */
	createdAt?: string | null
	/**
	 * Forcepasswordreset
	 */
	forcePasswordReset?: boolean
}

/**
 * UserRegister
 */
export type UserRegister = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Password
	 */
	password: string
	/**
	 * Fullname
	 */
	fullName?: string | null
}

/**
 * UserUpdate
 */
export type UserUpdate = {
	/**
	 * Email
	 */
	email?: string | null
	/**
	 * Isactive
	 */
	isActive?: boolean
	/**
	 * Issuperuser
	 */
	isSuperuser?: boolean
	/**
	 * Fullname
	 */
	fullName?: string | null
	/**
	 * Password
	 */
	password?: string | null
	/**
	 * Forcepasswordreset
	 */
	forcePasswordReset?: boolean | null
}

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
	/**
	 * Fullname
	 */
	fullName?: string | null
	/**
	 * Email
	 */
	email?: string | null
	/**
	 * Lastviewedcds
	 */
	lastViewedCds?: string | null
}

/**
 * UsersPublic
 */
export type UsersPublic = {
	/**
	 * Data
	 */
	data: Array<UserPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>
	/**
	 * Message
	 */
	msg: string
	/**
	 * Error Type
	 */
	type: string
	/**
	 * Input
	 */
	input?: unknown
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown
	}
}

export type LoginLoginAccessTokenData = {
	body: BodyLoginLoginAccessToken
	path?: never
	query?: never
	url: '/api/v1/login/access-token'
}

export type LoginLoginAccessTokenErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginLoginAccessTokenError =
	LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors]

export type LoginLoginAccessTokenResponses = {
	/**
	 * Successful Response
	 */
	200: Token
}

export type LoginLoginAccessTokenResponse =
	LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses]

export type LoginTestTokenData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/login/test-token'
}

export type LoginTestTokenResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses]

export type LoginRecoverPasswordData = {
	body?: never
	path: {
		/**
		 * Email
		 */
		email: string
	}
	query?: never
	url: '/api/v1/password-recovery/{email}'
}

export type LoginRecoverPasswordErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors]

export type LoginRecoverPasswordResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type LoginRecoverPasswordResponse =
	LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses]

export type LoginResetPasswordData = {
	body: NewPassword
	path?: never
	query?: never
	url: '/api/v1/reset-password/'
}

export type LoginResetPasswordErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors]

export type LoginResetPasswordResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type LoginResetPasswordResponse =
	LoginResetPasswordResponses[keyof LoginResetPasswordResponses]

export type LoginRecoverPasswordHtmlContentData = {
	body?: never
	path: {
		/**
		 * Email
		 */
		email: string
	}
	query?: never
	url: '/api/v1/password-recovery-html-content/{email}'
}

export type LoginRecoverPasswordHtmlContentErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginRecoverPasswordHtmlContentError =
	LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors]

export type LoginRecoverPasswordHtmlContentResponses = {
	/**
	 * Successful Response
	 */
	200: string
}

export type LoginRecoverPasswordHtmlContentResponse =
	LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses]

export type LoginForcePasswordResetForUsersData = {
	body: ForcePasswordResetRequest
	path?: never
	query?: never
	url: '/api/v1/login/force-password-reset'
}

export type LoginForcePasswordResetForUsersErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginForcePasswordResetForUsersError =
	LoginForcePasswordResetForUsersErrors[keyof LoginForcePasswordResetForUsersErrors]

export type LoginForcePasswordResetForUsersResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type LoginForcePasswordResetForUsersResponse =
	LoginForcePasswordResetForUsersResponses[keyof LoginForcePasswordResetForUsersResponses]

export type UsersReadUsersData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/users/'
}

export type UsersReadUsersErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors]

export type UsersReadUsersResponses = {
	/**
	 * Successful Response
	 */
	200: UsersPublic
}

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses]

export type UsersCreateUserData = {
	body: UserCreate
	path?: never
	query?: never
	url: '/api/v1/users/'
}

export type UsersCreateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors]

export type UsersCreateUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses]

export type UsersDeleteUserMeData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/users/me'
}

export type UsersDeleteUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses]

export type UsersReadUserMeData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/users/me'
}

export type UsersReadUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses]

export type UsersUpdateUserMeData = {
	body: UserUpdateMe
	path?: never
	query?: never
	url: '/api/v1/users/me'
}

export type UsersUpdateUserMeErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors]

export type UsersUpdateUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses]

export type UsersUpdatePasswordMeData = {
	body: UpdatePassword
	path?: never
	query?: never
	url: '/api/v1/users/me/password'
}

export type UsersUpdatePasswordMeErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdatePasswordMeError =
	UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors]

export type UsersUpdatePasswordMeResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type UsersUpdatePasswordMeResponse =
	UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses]

export type UsersGetUserPreferencesData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/users/me/preferences'
}

export type UsersGetUserPreferencesResponses = {
	/**
	 * Successful Response
	 */
	200: UserPreferencesUpdate
}

export type UsersGetUserPreferencesResponse =
	UsersGetUserPreferencesResponses[keyof UsersGetUserPreferencesResponses]

export type UsersUpdateUserPreferencesData = {
	body: UserPreferencesUpdate
	path?: never
	query?: never
	url: '/api/v1/users/me/preferences'
}

export type UsersUpdateUserPreferencesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdateUserPreferencesError =
	UsersUpdateUserPreferencesErrors[keyof UsersUpdateUserPreferencesErrors]

export type UsersUpdateUserPreferencesResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersUpdateUserPreferencesResponse =
	UsersUpdateUserPreferencesResponses[keyof UsersUpdateUserPreferencesResponses]

export type UsersRegisterUserData = {
	body: UserRegister
	path?: never
	query?: never
	url: '/api/v1/users/signup'
}

export type UsersRegisterUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors]

export type UsersRegisterUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses]

export type UsersDeleteUserData = {
	body?: never
	path: {
		/**
		 * User Id
		 */
		user_id: string
	}
	query?: never
	url: '/api/v1/users/{user_id}'
}

export type UsersDeleteUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors]

export type UsersDeleteUserResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses]

export type UsersReadUserByIdData = {
	body?: never
	path: {
		/**
		 * User Id
		 */
		user_id: string
	}
	query?: never
	url: '/api/v1/users/{user_id}'
}

export type UsersReadUserByIdErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors]

export type UsersReadUserByIdResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses]

export type UsersUpdateUserData = {
	body: UserUpdate
	path: {
		/**
		 * User Id
		 */
		user_id: string
	}
	query?: never
	url: '/api/v1/users/{user_id}'
}

export type UsersUpdateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors]

export type UsersUpdateUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses]

export type UtilsTestEmailData = {
	body?: never
	path?: never
	query: {
		/**
		 * Email To
		 */
		email_to: string
	}
	url: '/api/v1/utils/test-email/'
}

export type UtilsTestEmailErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors]

export type UtilsTestEmailResponses = {
	/**
	 * Successful Response
	 */
	201: Message
}

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses]

export type UtilsHealthCheckData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/utils/health-check/'
}

export type UtilsHealthCheckResponses = {
	/**
	 * Response Utils-Health Check
	 *
	 * Successful Response
	 */
	200: boolean
}

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses]

export type ItemsReadItemsData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/items/'
}

export type ItemsReadItemsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors]

export type ItemsReadItemsResponses = {
	/**
	 * Successful Response
	 */
	200: ItemsPublic
}

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses]

export type ItemsCreateItemData = {
	body: ItemCreate
	path?: never
	query?: never
	url: '/api/v1/items/'
}

export type ItemsCreateItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors]

export type ItemsCreateItemResponses = {
	/**
	 * Successful Response
	 */
	200: ItemPublic
}

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses]

export type ItemsDeleteItemData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/items/{id}'
}

export type ItemsDeleteItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors]

export type ItemsDeleteItemResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses]

export type ItemsReadItemData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/items/{id}'
}

export type ItemsReadItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors]

export type ItemsReadItemResponses = {
	/**
	 * Successful Response
	 */
	200: ItemPublic
}

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses]

export type ItemsUpdateItemData = {
	body: ItemUpdate
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/items/{id}'
}

export type ItemsUpdateItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors]

export type ItemsUpdateItemResponses = {
	/**
	 * Successful Response
	 */
	200: ItemPublic
}

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses]

export type CensusdataCountOfCensusDataData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/censusdata/'
}

export type CensusdataCountOfCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataCountOfCensusDataError =
	CensusdataCountOfCensusDataErrors[keyof CensusdataCountOfCensusDataErrors]

export type CensusdataCountOfCensusDataResponses = {
	/**
	 * Response Censusdata-Count Of Census Data
	 *
	 * Successful Response
	 */
	200: Array<CensusData>
}

export type CensusdataCountOfCensusDataResponse =
	CensusdataCountOfCensusDataResponses[keyof CensusdataCountOfCensusDataResponses]

export type CensusdataCreateCensusDataData = {
	body: CensusData
	path?: never
	query?: never
	url: '/api/v1/censusdata/'
}

export type CensusdataCreateCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataCreateCensusDataError =
	CensusdataCreateCensusDataErrors[keyof CensusdataCreateCensusDataErrors]

export type CensusdataCreateCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataCreateCensusDataResponse =
	CensusdataCreateCensusDataResponses[keyof CensusdataCreateCensusDataResponses]

export type CensusdataDeleteCensusDataData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/censusdata/{id}'
}

export type CensusdataDeleteCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataDeleteCensusDataError =
	CensusdataDeleteCensusDataErrors[keyof CensusdataDeleteCensusDataErrors]

export type CensusdataDeleteCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataDeleteCensusDataResponse =
	CensusdataDeleteCensusDataResponses[keyof CensusdataDeleteCensusDataResponses]

export type CensusdataReadCensusDataData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/censusdata/{id}'
}

export type CensusdataReadCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataReadCensusDataError =
	CensusdataReadCensusDataErrors[keyof CensusdataReadCensusDataErrors]

export type CensusdataReadCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataReadCensusDataResponse =
	CensusdataReadCensusDataResponses[keyof CensusdataReadCensusDataResponses]

export type CensusdataUpdateCensusDataData = {
	body: CensusData
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/censusdata/{id}'
}

export type CensusdataUpdateCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataUpdateCensusDataError =
	CensusdataUpdateCensusDataErrors[keyof CensusdataUpdateCensusDataErrors]

export type CensusdataUpdateCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataUpdateCensusDataResponse =
	CensusdataUpdateCensusDataResponses[keyof CensusdataUpdateCensusDataResponses]

export type SchoolsReadSchoolsData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Q
		 */
		q?: string | null
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/schools/'
}

export type SchoolsReadSchoolsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type SchoolsReadSchoolsError = SchoolsReadSchoolsErrors[keyof SchoolsReadSchoolsErrors]

export type SchoolsReadSchoolsResponses = {
	/**
	 * Successful Response
	 */
	200: SchoolsPublic
}

export type SchoolsReadSchoolsResponse =
	SchoolsReadSchoolsResponses[keyof SchoolsReadSchoolsResponses]

export type SchoolsReadSchoolsSummaryData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Q
		 */
		q?: string | null
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/schools/summary'
}

export type SchoolsReadSchoolsSummaryErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type SchoolsReadSchoolsSummaryError =
	SchoolsReadSchoolsSummaryErrors[keyof SchoolsReadSchoolsSummaryErrors]

export type SchoolsReadSchoolsSummaryResponses = {
	/**
	 * Successful Response
	 */
	200: SchoolsSummary
}

export type SchoolsReadSchoolsSummaryResponse =
	SchoolsReadSchoolsSummaryResponses[keyof SchoolsReadSchoolsSummaryResponses]

export type DashboardGetDashboardSummaryData = {
	body?: never
	path?: never
	query: {
		/**
		 * Cds
		 */
		cds: string
		/**
		 * Reportingyear
		 */
		reportingYear?: string
		/**
		 * Studentgroup
		 */
		studentGroup?: string
	}
	url: '/api/v1/dashboard/summary'
}

export type DashboardGetDashboardSummaryErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type DashboardGetDashboardSummaryError =
	DashboardGetDashboardSummaryErrors[keyof DashboardGetDashboardSummaryErrors]

export type DashboardGetDashboardSummaryResponses = {
	/**
	 * Successful Response
	 */
	200: DashboardSummaryResponse
}

export type DashboardGetDashboardSummaryResponse =
	DashboardGetDashboardSummaryResponses[keyof DashboardGetDashboardSummaryResponses]

export type DashboardGetEquityReportData = {
	body?: never
	path?: never
	query: {
		/**
		 * Cds
		 */
		cds: string
		/**
		 * Testid
		 */
		testId: string
		/**
		 * Reportingyear
		 */
		reportingYear?: string
	}
	url: '/api/v1/dashboard/equity'
}

export type DashboardGetEquityReportErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type DashboardGetEquityReportError =
	DashboardGetEquityReportErrors[keyof DashboardGetEquityReportErrors]

export type DashboardGetEquityReportResponses = {
	/**
	 * Successful Response
	 */
	200: EquityReportResponse
}

export type DashboardGetEquityReportResponse =
	DashboardGetEquityReportResponses[keyof DashboardGetEquityReportResponses]

export type PrivateCreateUserData = {
	body: PrivateUserCreate
	path?: never
	query?: never
	url: '/api/v1/private/users/'
}

export type PrivateCreateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors]

export type PrivateCreateUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses]
